# Generated by Django 3.2.9 on 2022-01-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('codeClass', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('libClass', models.CharField(max_length=30, unique=True)),
                ('capacite', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Classe',
                'db_table': 'CLASSE',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('numEns', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomEns', models.CharField(max_length=30)),
                ('prenomEns', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=25)),
                ('anneePriseFonction', models.IntegerField(db_column='anneePriseFonction', default=2022)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'ENSEIGNANT',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('numEtu', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomEtud', models.CharField(max_length=50)),
                ('prenomEtud', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('dateNaissance', models.DateField()),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
                'db_table': 'ETUDIANT',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('codeEval', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libEval', models.CharField(max_length=50, unique=True)),
                ('pourcentage', models.IntegerField(default=range(0, 100))),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'db_table': 'EVALUATION',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('codeMod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libMod', models.CharField(max_length=100, unique=True)),
                ('nbCredit', models.IntegerField()),
                ('est_requis', models.BooleanField()),
                ('annneeCreation', models.IntegerField(db_column='anneeCreation', default=2022)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'MODULE',
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('codeParc', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('libParc', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'db_table': 'PARCOURS',
            },
        ),
        migrations.CreateModel(
            name='Noter',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.FloatField(blank=True, null=True)),
                ('valide', models.BooleanField(blank=True, null=True)),
                ('dateEval', models.DateField(db_column='dateEval')),
                ('codeEval', models.ForeignKey(db_column='codeEval', on_delete=django.db.models.deletion.RESTRICT, to='etudes.evaluation')),
                ('codeMod', models.ForeignKey(db_column='codeMod', on_delete=django.db.models.deletion.RESTRICT, to='etudes.module')),
                ('numEtu', models.OneToOneField(db_column='numEtu', on_delete=django.db.models.deletion.RESTRICT, to='etudes.etudiant')),
            ],
            options={
                'verbose_name': 'Noter',
                'verbose_name_plural': 'Noter',
                'db_table': 'NOTER',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('codeNiv', models.BigAutoField(primary_key=True, serialize=False)),
                ('libNiv', models.CharField(max_length=50, unique=True)),
                ('nbModules', models.IntegerField(db_column='nbreModule', default=0)),
                ('codeParc', models.ForeignKey(db_column='codeParc', on_delete=django.db.models.deletion.CASCADE, to='etudes.parcours')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'db_table': 'NIVEAU',
            },
        ),
        migrations.CreateModel(
            name='ModuleRequis',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codeMod', models.ForeignKey(db_column='codeMod', on_delete=django.db.models.deletion.RESTRICT, related_name='codeModule', to='etudes.module')),
                ('codePrerequis', models.ForeignKey(db_column='codeModRequis', on_delete=django.db.models.deletion.RESTRICT, related_name='codeRequis', to='etudes.module')),
            ],
            options={
                'verbose_name': 'Module requis',
                'verbose_name_plural': 'Module requis',
                'db_table': 'MODULES_REQUIS',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='codeNiv',
            field=models.ForeignKey(db_column='codeNiv', on_delete=django.db.models.deletion.RESTRICT, to='etudes.niveau'),
        ),
        migrations.CreateModel(
            name='Inscrire',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anneeIns', models.IntegerField(default=2022)),
                ('codeNiv', models.ForeignKey(db_column='CodeNiv', on_delete=django.db.models.deletion.RESTRICT, to='etudes.niveau')),
                ('numEtu', models.ForeignKey(db_column='NumEtu', on_delete=django.db.models.deletion.RESTRICT, to='etudes.etudiant', unique=True)),
            ],
            options={
                'verbose_name': 'Inscrire',
                'verbose_name_plural': 'Inscrires',
                'db_table': 'INSCRIRE',
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='codeParc',
            field=models.ForeignKey(db_column='codeParc', on_delete=django.db.models.deletion.CASCADE, to='etudes.parcours'),
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('annneeDisp', models.IntegerField(db_column='anneeDisp', default=2022)),
                ('codeMod', models.ForeignKey(db_column='codeMod', on_delete=django.db.models.deletion.RESTRICT, to='etudes.module')),
                ('codeclass', models.ForeignKey(db_column='codeClass', on_delete=django.db.models.deletion.RESTRICT, to='etudes.classe')),
                ('numEns', models.ForeignKey(db_column='numEns', on_delete=django.db.models.deletion.RESTRICT, to='etudes.enseignant')),
            ],
            options={
                'verbose_name': 'Dispenser',
                'verbose_name_plural': 'Dispenser',
                'db_table': 'DISPENSER',
            },
        ),
    ]
