# Generated by Django 3.2.9 on 2022-01-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='libParc',
            field=models.CharField(max_length=100),
        ),
    ]
